### ISSUE TITLE
JSON1 OT Diff

### ISSUE THREAD

**Issue by marcusnewton** [kbadk/json0-ot-diff#11]
[json1](https://github.com/ottypes/json1) seems to be getting more attention lately, would be great to see a differ for json1 and/or advice on how we can contribute.

I'm not well-versed in OT stuff, but this library looks relatively straightforward, which is promising for JSON1

**Comment by curran** [comment]
From [Interoperability with JSON0](https://github.com/ottypes/json1#interoperability-with-json0):

> You can convert JSON0 operations to JSON1 operations using [json0-to-1](https://github.com/ottypes/json0-to-1). This is a work in progress and doesn't currently support converting string values. 

I haven't tried it, but in theory the output from `json0-ot-diff` could be passed through `json0-to-1` to get `json1` ops.

**Comment by curran** [comment]
Anyone tried this?

**Comment by curran** [comment]
Got it working! https://github.com/kbadk/json0-ot-diff/pull/16
