### ISSUE TITLE
About support browser environment

### ISSUE THREAD

**Issue by lijie1129** [kbadk/json0-ot-diff#15]
hi，I use [json0-ot-diff](https://github.com/kbadk/json0-ot-diff) recently.

And I found the `json0-ot-diff` only supports the NodeJS environment.

so I think why the `json0-ot-diff` doesn't run Browser environment.

I find the reason is the dependency `deep-equal` doesn't support the Browser environment，therefore, the `json0-ot-diff` is restricted by `deep-equal`.

Can the `json0-ot-diff` provide an option to replace `deep-equal` with another library? (like isEqual of Lodash.) This will support more environments.  :)

**Comment by curran** [comment]
I've been using this library in a browser environment for a while now with no issues.

Can you share a minimal reproduction of the issue in a repository?

It may depend on what build tools you are using.

**Comment by kbadk** [comment]
Is this a problem that has come up as a result of [the upgrade from `deep-equal` v1 to v2](https://github.com/kbadk/json0-ot-diff/commit/623ab7d0d8924413e2c654b20cfaf708ff901649)? In other words, are you seeing the same problems with `json0-ot-diff` v1.0.5?

**Comment by lijie1129** [comment]
hi @curran @kbadk 

My Environment:

```javascript
➜  my-web-app cat package.json
{
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "json0-ot-diff": "^1.0.7",
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.2.4",
    "@vue/compiler-sfc": "^3.0.5",
    "vite": "^2.4.0"
  }
}

➜  my-web-app cat vite.config.js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()]
})

➜  my-web-app cat src/main.js
import { createApp } from 'vue'
import App from './App.vue'
import jsondiff from 'json0-ot-diff';

console.log(jsondiff);

createApp(App).mount('#app')

➜  my-web-app yarn dev
```

when my-web-app running in dev model,  I got this error:

![image](https://user-images.githubusercontent.com/5371749/124859376-6aa91180-dfe2-11eb-9a5c-8e1033feb566.png)


About create my-web-app, reference: https://vitejs.dev/guide/#scaffolding-your-first-vite-project

**Comment by kbadk** [comment]
So this problem was indeed introduced with the upgrade to `deep-equal` 2.

**Comment by kbadk** [comment]
This problem was introduced in https://github.com/kbadk/json0-ot-diff/pull/14. I've downgraded `deep-equal` to v1. If you upgrade to v1.0.8, you'll be rid of the problem.

This also removes the bulk the `deep-equal` upgrade introduced: [`deep-equal@1.1.1` 7.5kB](https://bundlephobia.com/package/deep-equal@1.1.1) vs [`deep-equal@2.0.5` 49.8kB](https://bundlephobia.com/package/deep-equal@2.0.5).

Thanks for making us aware of the problem.

**Comment by curran** [comment]
Wow the bloat trajectory on `deep-equal` is insane!

![image](https://user-images.githubusercontent.com/68416/125113860-2f2c4700-e0b7-11eb-898d-d187b5f453a5.png)

It's mind boggling to me why a deep equal implementation would be so large.
