### ISSUE TITLE
Running diff from null to object fails.

### ISSUE THREAD

**Issue by JakubSerwatka** [kbadk/json0-ot-diff#24]
Hi, I've noticed an inconsistency when it comes to handling diffing between null and another type. Following code will succeed
```
const before = {a: null};
const after = {a: 1};
const op = jd(before, after);
console.log(op);

//Outputs [{"p":["a"],"od":null,"oi":1}] 
```
Same goes for `const after = {a: "text"}`

But following will fail
```
const before = { a: null };
const after = { a: {} };
const op = jd(before, after);
console.log(JSON.stringify(op));
```

with an error 

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
   at diff (https://du8wr.csb.app/node_modules/json0-ot-diff/index.js:196:32)
```

I've managed to track it down to this line
```var keys = new Set([...Object.keys(input), ...Object.keys(output)]);```

`Object.keys(input)` fails due `input` being null

My expected behaviour is that the diff will behave exactly as when undefined and just generate `oi` operation at specified path.

**Comment by curran** [comment]
Great find! Adding a failing test would be the first step.
